version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_network

  webserver:
    image: nginx:latest
    container_name: nginx_webserver
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
