services:
  - type: web
    name: laravel-app
    env: docker
    plan: basic
    dockerfilePath: ./Dockerfile
    buildCommand: composer install && npm install && npm run build
    startCommand:  php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_KEY
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://urscholar.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.wwecpxfveikhrbnsfuwf.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: JaczM840OhZ5wUrN
